name: my-workflow

on:
  push:
    branches:
      - "*"

jobs:
  lint-and-test:
    name: Lint and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1
      - name: Install
        run: bun install
      - name: Lint
        run: bun lint
      - name: Test
        run: bun test
